### ISSUE TITLE
New band group not correctly considered for band subset

### ISSUE THREAD

**Issue by eomasters-repos** [senbox-org/optical-toolbox#78]
In SNAP 11 dev version I've created a new band group for Sentinel-2 bands.

![image](https://github.com/user-attachments/assets/b4eea28e-0443-4426-b81d-8292a124fc81)

It seems this is not correctly applied. First, I use the checkbox to select none of the bands.
Then I use the checkbox to select the bands of the selected group and afterwards all bands are selected.

![image](https://github.com/user-attachments/assets/4729bc0e-b4a5-4993-b67d-5785415f4d8f)

![image](https://github.com/user-attachments/assets/27dbb213-96a0-4480-b44e-5ae1844f3fa5)

**Comment by dianaharosa** [comment]
Could not reproduce with the released SNAP 11

**Comment by eomasters-repos** [comment]
I can still reproduce it.
In my band group only B1, B2, B3 and B4 are defined, but B11 and B12 are selected too. Also, other bands containing B1, B2 or B4.
![image](https://github.com/user-attachments/assets/5a0be9c0-b67b-45c8-bdc8-5adfde072433)

The problem probably is that it is checked if the band name **contains** the name defined by the band group and not if it exactly matches.

**Comment by dianaharosa** [comment]
Jira ticket [SNAP-3892](https://senbox.atlassian.net/browse/SNAP-3892) created
